### ISSUE TITLE
Problem with special characters.

### ISSUE THREAD

**Issue by Denisov21** [jadbox/brackets-integrated-development#2]
1. Open Brackets
2. Click on RUN

Error: as you can see the red arrow indicates a symbol is not supported! Change this character with "é"

Win 7 32 bit, language Italian

![immagine 001 20052014](https://cloud.githubusercontent.com/assets/2547815/3032695/16204842-e05b-11e3-8018-0248f530f08d.png)

**Comment by jadbox** [comment]
I tested this in v0.5.57 of the extension and couldn't reproduce the issue with special chars like é in either a success or error scenario. Can you retest and reopen if this is still a bug?

**Comment by Denisov21** [comment]
@jadbox Reopen conferm bug on v0.5.57.
I think the correct encoding to display these characters is "utf-8"
