### ISSUE TITLE
Brackets Integrated Development "node: command not found"

### ISSUE THREAD

**Issue by kopylovvlad** [jadbox/brackets-integrated-development#21]
I have installed Integrated Development on Brackets.
I can run php or ruby code. But if I want run js code i see "/bin/sh: node: command not found". It's  curiously. I have installed node on my macbook. I can run js code on sublimetext and i can run js code on console line "node <filename>". But why do i see error in Brackets.
I didn't change file builder.json.
Please help me.

**Comment by thurstjo63** [comment]
I have the same problem.
