### ISSUE TITLE
Configuration JavaScript

### ISSUE THREAD

**Issue by Denisov21** [jadbox/brackets-integrated-development#3]
Windows 7
Hi,
Can you explain better once you open the file "builder.json" how do I change the compiler for JavaScript? Thank you!

**Comment by roubarbe** [comment]
It's automatic if you have Node installed, and well set in your global path.

See here: http://geekswithblogs.net/renso/archive/2009/10/21/how-to-set-the-windows-path-in-windows-7.aspx

**Comment by jadbox** [comment]
@Denisov21 Did @roubarbe answer help?

**Comment by Denisov21** [comment]
@jadbox Perfect, I solved!
@roubarbe Thank you!
