### ISSUE TITLE
Styling of errors in code impossible to read

### ISSUE THREAD

**Issue by EvHaus** [jadbox/brackets-integrated-development#4]
Thanks for the extension, it's pretty great! However, I've had to disable it due to one very small problem. The styling of errors in the code body makes it impossible to read them.

For example, type `"<p>&</p>"` in any HTML file and the ampersand will appear as red text on a red background (this is correct, as it should be `&nbsp;`). But the red or red styling  means I have no idea what the error is or how to fix it -- because I can't see it!

If you could fix this small issue, that would be great.

**Comment by jadbox** [comment]
This is pretty hard to fix on my end. Ideally, the "cm-error" CSS class that is used in the default themes (and theme extensions) should provide the ideal styling. For example, the red highlight may not even be ideal if the themed background is a red-ish color. I'll check though if there's a better option on my end however and update this issue.

**Comment by EvHaus** [comment]
Ah, I didn't think it was a Brackets styling issue. Do we need to kick this up to them?

**Comment by jadbox** [comment]
Okay, I think I found a way on my side with v0.5.57. On the default theme, the background color for the error should be a darker red now, allowing you to read the text. Let me know if you think this needs to be reopened. :)

**Comment by EvHaus** [comment]
Better, but still hard to see, and I'm not even an old person :)

How about same background color, but white text?
