### ISSUE TITLE
Option to run on save or continuously

### ISSUE THREAD

**Issue by peppy** [jadbox/brackets-integrated-development#6]
Running manually isn't too useful. It would be nice to have the option to automatically run on save, or even better, asynchronously in the background after 0.x seconds of no keyboard input.

**Comment by jadbox** [comment]
Yep, I'll plan on adding this in a new update unless I get a pull request with it. ;)

**Comment by jadbox** [comment]
Added for compile-on-save! Just set IDE.autocompile in your project prefs (see readme.md)... the next version will allow you to lock autocompiling to a specific file. I'll close this task once that's implemented.

**Comment by jadbox** [comment]
I've now added the target file locking for autocompile (see the readme). You'll have to specify the file type as it's name in the builder.json config file.

While this doesn't save on a timer, I think it'll be better to stick with "on save" so that the compiler doesn't slow down the editor.
