### ISSUE TITLE
Idea: I wish support to HTML and javascript!

### ISSUE THREAD

**Issue by Denisov21** [jadbox/brackets-integrated-development#7]
for example I have this file ifsample.htm:

I would love if your extension found errors in a file like this. In image there is an error not report!! 

![immagine 001 22052014](https://cloud.githubusercontent.com/assets/2547815/3058618/31e17988-e1e2-11e3-8aca-a0211ce14445.png)

**Comment by jadbox** [comment]
Hmm.. let me see what I can do for ya. I'll see if I can get Node to consume the file directly. Check back soon :]

**Comment by jadbox** [comment]
Sadly there's no way to make this work. 1) There's no way to directly interpret the js-in-html file with node and 2) related to the previous point, you can't run the function without a browser interpreting it. However there is hope: either refactor your code into a standalone JS file to test OR use the Live Debugging feature in Brackets and check the Chrome Developer Console (once the page is rendered). Hope this helps put you on the right direction!
